<a href="https://colab.research.google.com/github/bharathkumaro5/Numpy/blob/main/bharathkumar.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Getting Familiar with NumPy

In [2]:
import numpy as np
array = np.array([1, 2, 3, 4, 5])
print("Array:", array)
array_squared = array ** 2
print("Array Squared:", array_squared)
print("Shape:", array.shape)
print("Data Type:", array.dtype)
print("Size:", array.size)
print("Number of Dimensions:", array.ndim)

Array: [1 2 3 4 5]
Array Squared: [ 1  4  9 16 25]
Shape: (5,)
Data Type: int64
Size: 5
Number of Dimensions: 1


2. Data Manipulation(
performing indexing,slicing,and reshaping)

In [4]:
import numpy as np
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("\n2D Array (Matrix):\n", matrix)
# Indexing
element = matrix[1, 2]
print("\nElement at [1, 2]:", element)
# Slicing
sub_matrix = matrix[:2, 1:]  # first 2 rows, last 2 columns
print("\nSliced Sub-Matrix:\n", sub_matrix)
# Reshaping
reshaped_matrix = matrix.reshape(1, 9)
print("\nReshaped Matrix:\n", reshaped_matrix)


2D Array (Matrix):
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Element at [1, 2]: 6

Sliced Sub-Matrix:
 [[2 3]
 [5 6]]

Reshaped Matrix:
 [[1 2 3 4 5 6 7 8 9]]


3. Data Aggregation(finding mean,median and standard deviation)

In [6]:
import numpy as np
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
mean = np.mean(matrix)
median = np.median(matrix)
std_dev = np.std(matrix)
total_sum = np.sum(matrix)
print("\nMean:", mean)
print("Median:", median)
print("Standard Deviation:", std_dev)
print("Total Sum:", total_sum)
row_sums = np.sum(matrix, axis=1)
print("\nSum of Each Row:", row_sums)


Mean: 5.0
Median: 5.0
Standard Deviation: 2.581988897471611
Total Sum: 45

Sum of Each Row: [ 6 15 24]


4. Data Analysis(finding correlation matrix and percentiles)


In [7]:
import numpy as np
data = np.random.rand(10, 3)
correlation_matrix = np.corrcoef(data, rowvar=False)
print("\nCorrelation Matrix:\n", correlation_matrix)
outliers = np.where(matrix > 8)
print("\nOutliers (values greater than 8):", matrix[outliers])
# Percentiles
percentiles = np.percentile(matrix, [25, 50, 75])
print("\n25th, 50th, and 75th Percentiles:", percentiles)


Correlation Matrix:
 [[1.         0.02744785 0.03696289]
 [0.02744785 1.         0.26096656]
 [0.03696289 0.26096656 1.        ]]

Outliers (values greater than 8): [9]

25th, 50th, and 75th Percentiles: [3. 5. 7.]


**Application in Data Science:**
NumPy's powerful numerical operations and array handling make it essential for data science.

Performance: NumPy's operations are implemented in C, making them significantly faster than equivalent Python code.

Vectorization: NumPy supports vectorized operations, which allow you to perform element-wise operations efficiently.
Memory Efficiency: NumPy arrays are more memory-efficient compared to traditional Python lists, especially for large datasets.

NumPy provides a powerful array object and a suite of mathematical functions that make it a cornerstone in data manipulation and analysis. Its efficiency and functionality are critical in fields that require numerical computations and data handling.